name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
          tags: |
            type=semver,pattern={{version}}
      - name: test tags
        run: echo "${{ steps.meta.outputs.tags }}"
      - name: test labels
        run: echo "${{ steps.meta.outputs.labels }}"
